language: python

sudo: false

env:
  - TOX_ENV=py27
  - TOX_ENV=py32
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py35
  
matrix:
  allow_failures:
    - env: TOX_ENV=py35

install:
  - pip install tox
  - pip install codecov

script:
  - tox -e $TOX_ENV

after_success:
  - codecov -e TOX_ENV
